### ISSUE TITLE
StartPage monitore size: three columns, head is over all columns and includes a clock.

### ISSUE THREAD

**Issue by schmulski** [schmulski/buzz-board#1]
![15745931634235172875277678731853](https://user-images.githubusercontent.com/6508837/69493681-e0b24080-0eb1-11ea-869d-df32ec4de8b3.jpg)
1. column:
_ everything about people - birthdays, new employees, anniversary, leaver

2. column:
Weekly events:
- team breakfast, all hands, team lunch, afterwork bear, ping pong events, big stand up, 

3. column: 
- lunch recommendations, and uptodate hvv tweets

**Comment by geekmaedchen** [comment]
@schmulski Code is great! The clock is missing. And please remember to use a feature branch.
